name: Context-workflows

on: ['push']

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps: 
      - name: "My Step"
        run: |
          echo "Actions $MY_ACTION"
          echo "Actor $MY_ACTOR"
          echo "JOB_STATUS $MY_JOB_STATUS"
        env:
          MY_ACTIONS: ${{ github.action }}
          MY_ACTOR: ${{ github.actor }}
          MY_JOB_STATUS: ${{ job.status }}
